# Generated by Django 6.0.6 on 2026-08-19 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_zona_ve_todas', models.BooleanField(default=True, help_text='Cuando un usuario todavía no tiene zona ni acceso nacional, en vez de dejarlo sin nada le muestra todas las tiendas y todos los expedientes. Desactivalo si preferís que un usuario a medio configurar no vea nada hasta asignarle su zona. No cambia lo que puede hacer: borrar sigue siendo solo del Administrador.', verbose_name='Sin zona asignada: ver todas las tiendas')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferencias del sistema',
                'verbose_name_plural': 'preferencias del sistema',
            },
        ),
    ]
