# Generated by Django 6.0.6 on 2026-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='sin_zona_ve_todas',
        ),
        migrations.AddField(
            model_name='preferencias',
            name='restringir_por_zona',
            field=models.BooleanField(default=False, help_text='Apagado (como viene), todos ven todas las tiendas y todos los expedientes, sin importar la zona. Prendelo solo si algún día querés que cada usuario vea únicamente los expedientes de su zona. No cambia lo que cada uno puede hacer: borrar sigue siendo solo del Administrador.', verbose_name='Restringir cada usuario a su zona'),
        ),
    ]
