# Generated by Django 6.0.6 on 2026-08-23 14:50

"""Cuantos dias esperar antes de barrer solo los documentos marcados.

En 0 -como viene- no se borra nada solo: decide una persona.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_preferencias_sin_zona_ve_todas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='dias_para_eliminar_marcados',
            field=models.PositiveIntegerField(default=0, help_text='Cuántos días esperar antes de que un documento marcado para eliminar se vaya solo a la papelera. En 0 no se borra nada solo: la lista de pendientes queda esperando que alguien decida. Va a la papelera, no se pierde: el Administrador puede restaurarlo desde el expediente.', verbose_name='Días para eliminar los documentos marcados'),
        ),
    ]
