# Generated by Django 6.0.6 on 2026-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_plazo_para_eliminar_marcados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='dias_para_eliminar_marcados',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Cuántos días esperar antes de que un documento marcado para eliminar se vaya solo a la papelera. En 0 no se borra nada solo: la lista de pendientes queda esperando que alguien decida. Va a la papelera, no se pierde: el Administrador puede restaurarlo desde el expediente.', verbose_name='Días para eliminar los documentos marcados'),
        ),
    ]
