# Generated by Django 5.1.15 on 2026-07-06 20:27

import cuentas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=cuentas.models._generar_token, editable=False, help_text='Se genera automáticamente. Forma parte del link de registro.', max_length=64, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador (Sede Central)'), ('RRHH_INTERIOR', 'RRHH Interior (zona restringida)'), ('SOLO_LECTURA', 'Solo lectura')], help_text='Rol con el que quedará la persona que use este link.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Opcional: a quién se le envió (solo informativo).', max_length=254)),
                ('nota', models.CharField(blank=True, help_text='Etiqueta opcional para identificar la invitación.', max_length=120)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(default=cuentas.models._expiracion_por_defecto)),
                ('activa', models.BooleanField(default=True)),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('usada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_usada', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, help_text='Obligatoria para RRHH Interior y Solo lectura (define su alcance).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='cuentas.zona')),
            ],
            options={
                'verbose_name': 'invitación de registro',
                'verbose_name_plural': 'invitaciones de registro',
                'ordering': ['-creada_en'],
            },
        ),
    ]
