# Generated by Django 6.0.6 on 2026-07-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_invitacionregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='invitacionregistro',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento con el que quedará la persona que use este link (informativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones', to='cuentas.departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Área/departamento del usuario. Informativo (no afecta permisos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cuentas.departamento'),
        ),
    ]
