# Generated by Django 6.0.6 on 2026-08-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionregistro',
            name='acceso_nacional',
            field=models.BooleanField(default=False, help_text='La persona verá las tiendas y los expedientes de todo el país. Con esto tildado no hace falta elegir zona.', verbose_name='acceso a todas las zonas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_nacional',
            field=models.BooleanField(default=False, help_text='Para RRHH Interior o Solo lectura que trabajan con todo el país: ven las tiendas y los expedientes de todas las zonas. Con esto tildado la zona no hace falta.', verbose_name='acceso a todas las zonas'),
        ),
        migrations.AlterField(
            model_name='invitacionregistro',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para RRHH Interior y Solo lectura, salvo que se les dé acceso a todas las zonas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='cuentas.zona'),
        ),
    ]
