# Generated by Django 6.0.6 on 2026-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_invitacionregistro_acceso_nacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionregistro',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Sede Central)'), ('RRHH_INTERIOR', 'RRHH Interior (carga y edita)'), ('SOLO_LECTURA', 'Solo lectura')], help_text='Rol con el que quedará la persona que use este link.', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Sede Central)'), ('RRHH_INTERIOR', 'RRHH Interior (carga y edita)'), ('SOLO_LECTURA', 'Solo lectura')], default='SOLO_LECTURA', max_length=20),
        ),
    ]
