# Generated by Django 6.0.6 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_invitacionregistro_rol_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='La letra que se antepone: V, E, J, P, G.', max_length=5, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Cómo se lee: Venezolano, Extranjero…', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=100, help_text='Menor primero en el desplegable.')),
            ],
            options={
                'verbose_name': 'tipo de cédula',
                'verbose_name_plural': 'tipos de cédula',
                'ordering': ['orden', 'codigo'],
            },
        ),
    ]
