# Generated by Django 6.0.6 on 2026-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_tipos_de_cedula_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, help_text="La ciudad donde esta la tienda: GUATIRE, VALENCIA, MARACAY. Es la que sale como lugar en los documentos ('GUATIRE, 24 de agosto de 2026'). Si se deja vacia sale la zona, que es el estado, asi que nunca queda en blanco.", max_length=120),
        ),
    ]
