# Generated by Django 6.0.8 on 2026-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_ciudad_de_la_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionregistro',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Sede Central)'), ('RRHH_INTERIOR', 'RRHH Interior (carga y edita)'), ('RRHH_PRINCIPAL', 'RRHH Principal (carga y edita)'), ('SOLO_LECTURA', 'Solo lectura')], help_text='Rol con el que quedará la persona que use este link.', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Sede Central)'), ('RRHH_INTERIOR', 'RRHH Interior (carga y edita)'), ('RRHH_PRINCIPAL', 'RRHH Principal (carga y edita)'), ('SOLO_LECTURA', 'Solo lectura')], default='SOLO_LECTURA', max_length=20),
        ),
    ]
