# Generated by Django 6.0.8 on 2026-08-28 18:26

import cuentas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_alter_invitacionregistro_rol_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, help_text='Opcional. Sirve para encontrar al usuario por la cédula de la persona en Configuración → Usuarios.', max_length=30, verbose_name='cédula'),
        ),
        migrations.CreateModel(
            name='RecuperacionClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=cuentas.models._generar_token, editable=False, max_length=64, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(default=cuentas.models._expiracion_recuperacion)),
                ('activa', models.BooleanField(default=True)),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'link de recuperación de clave',
                'verbose_name_plural': 'links de recuperación de clave',
                'ordering': ['-creada_en'],
            },
        ),
    ]
