# Generated by Django 6.0.8 on 2026-09-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_usuario_cedula_recuperacionclave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='es_general',
            field=models.BooleanField(default=True, help_text='Se ofrece en el desplegable de cargos de cualquier expediente. Se destilda en los cargos particulares de una unidad (los duplicados por tienda), asi el desplegable muestra cada nombre una sola vez. No afecta a los trabajadores que ya lo tienen asignado.', verbose_name='general (todas las tiendas)'),
        ),
    ]
