# Generated by Django 5.1.15 on 2026-07-02 15:48

import django.db.models.deletion
import expedientes.models
import expedientes.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('obligatorio', models.BooleanField(default=False, help_text='Si es obligatorio, cuenta para la completitud del expediente.')),
                ('requiere_vencimiento', models.BooleanField(default=False, help_text='Si vence (ej: carnet de salud), se pedirá fecha de vencimiento.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(help_text='CI / DNI. Identifica de forma única al trabajador.', max_length=30, unique=True, verbose_name='documento de identidad')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('puesto', models.CharField(blank=True, max_length=120)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='cuentas.sede')),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=expedientes.storage.AlmacenamientoCifrado(), upload_to=expedientes.models._ruta_documento, validators=[expedientes.models._validar_extension])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Borrado lógico: False = en papelera.')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='expedientes.tipodocumento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expedientes.trabajador')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_texto', models.CharField(blank=True, help_text='Copia del usuario por si se elimina la cuenta.', max_length=150)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FALLIDO', 'Inicio de sesión fallido'), ('LOGOUT', 'Cierre de sesión'), ('VER', 'Consulta'), ('DESCARGAR', 'Descarga de documento'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('SUBIR', 'Carga de documento'), ('BORRAR', 'Envío a papelera'), ('RESTAURAR', 'Restauración'), ('ACCESO_DENEGADO', 'Acceso denegado')], max_length=20)),
                ('entidad', models.CharField(blank=True, max_length=60)),
                ('objeto_id', models.CharField(blank=True, max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='expedientes_creado__351cbc_idx'), models.Index(fields=['accion'], name='expedientes_accion_bfe234_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['apellidos', 'nombres'], name='expedientes_apellid_3f15ec_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['documento_identidad'], name='expedientes_documen_e57f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['trabajador', 'tipo', 'activo'], name='expedientes_trabaja_9756c2_idx'),
        ),
    ]
