# Generated by Django 6.0.6 on 2026-07-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_departamento_invitacionregistro_departamento_and_more'),
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento/área en el que trabaja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='cuentas.departamento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='puesto',
            field=models.CharField(blank=True, max_length=120, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='cuentas.sede', verbose_name='tienda'),
        ),
    ]
