# Generated by Django 6.0.6 on 2026-07-29 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_trabajador_departamento_alter_trabajador_puesto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('clase', models.CharField(choices=[('SUELDO', 'Sueldo / salario'), ('BONO', 'Bono')], default='BONO', help_text='Solo agrupa el listado; no cambia los cálculos.', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'concepto de pago',
                'verbose_name_plural': 'conceptos de pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código ISO de 3 letras: VES, USD, EUR.', max_length=3, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=40)),
                ('simbolo', models.CharField(help_text='Bs, $, €', max_length=5, verbose_name='símbolo')),
                ('es_nacional', models.BooleanField(default=False, help_text='Marca la moneda del país. Las demás se consideran divisas.', verbose_name='es la moneda nacional')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libre', models.CharField(blank=True, help_text='Solo si no elegiste un concepto del catálogo.', max_length=120, verbose_name='nombre del bono extra')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Borrado lógico: False = dado de baja.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cargados', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='expedientes.trabajador')),
                ('concepto', models.ForeignKey(blank=True, help_text='Concepto del catálogo. Dejalo vacío para un bono extra con nombre libre.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='expedientes.conceptopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='expedientes.moneda')),
            ],
            options={
                'verbose_name': 'asignación de pago',
                'verbose_name_plural': 'asignaciones de pago',
                'ordering': [models.OrderBy(models.F('concepto__orden'), nulls_last=True), 'id'],
                'indexes': [models.Index(fields=['trabajador', 'activo'], name='expedientes_trabaja_6e4ee5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('concepto__isnull', False), ('nombre_libre', '')), models.Q(('concepto__isnull', True), models.Q(('nombre_libre', ''), _negated=True)), _connector='OR'), name='pago_concepto_del_catalogo_o_nombre_libre')],
            },
        ),
    ]
