# Generated by Django 6.0.6 on 2026-08-01 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_conceptopago_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO(A)', 'Soltero/a'), ('CASADO(A)', 'Casado/a'), ('DIVORCIADO(A)', 'Divorciado/a'), ('VIUDO(A)', 'Viudo/a'), ('CONCUBINO(A)', 'Concubino/a')], max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Domicilio del trabajador, como debe salir en el contrato.', max_length=400, verbose_name='dirección de habitación')),
                ('ciudad_nacimiento', models.CharField(blank=True, help_text='Ej: CARACAS, DISTRITO CAPITAL', max_length=150, verbose_name='ciudad de nacimiento')),
                ('horario', models.CharField(blank=True, help_text='Texto tal cual va en el contrato. Ej: 8:00AM a 5:00PM de lunes a sábado.', max_length=600, verbose_name='horario de trabajo')),
                ('motivo_contratacion', models.CharField(blank=True, help_text='Ej: Temporada Navidad, Temporada Día del Niño.', max_length=300, verbose_name='motivo de contratación')),
                ('fecha_culminacion', models.DateField(blank=True, null=True, verbose_name='fecha de culminación del contrato')),
                ('ciudad_firma', models.CharField(blank=True, default='CARACAS', max_length=120, verbose_name='ciudad de firma')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrataciones_editadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratacion', to='expedientes.trabajador')),
            ],
            options={
                'verbose_name': 'datos de contratación',
                'verbose_name_plural': 'datos de contratación',
            },
        ),
    ]
