# Generated by Django 6.0.6 on 2026-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_datoscontratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontratacion',
            name='banco',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='duracion_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Se puede cargar esto o la fecha de fin: el otro se calcula solo.', null=True, verbose_name='duración del contrato (días)'),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='numero_cuenta',
            field=models.CharField(blank=True, help_text='Los 16 dígitos restantes.', max_length=20, verbose_name='número de cuenta'),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='prefijo',
            field=models.CharField(blank=True, help_text='Los 4 primeros dígitos de la cuenta. Ej: 0102', max_length=4, verbose_name='prefijo del banco'),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='responsable',
            field=models.CharField(blank=True, help_text='Quién de RRHH procesó el ingreso.', max_length=150),
        ),
        migrations.AlterField(
            model_name='datoscontratacion',
            name='fecha_culminacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha fin de contrato'),
        ),
    ]
