# Generated by Django 5.1.15 on 2026-08-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_datoscontratacion_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontratacion',
            name='talla_camisa',
            field=models.CharField(blank=True, help_text='Ej: S, M, L, XL, 38.', max_length=10, verbose_name='talla de camisa'),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='talla_pantalon',
            field=models.CharField(blank=True, help_text='Ej: 30, 32, M.', max_length=10, verbose_name='talla de pantalón'),
        ),
        migrations.AddField(
            model_name='datoscontratacion',
            name='talla_zapato',
            field=models.CharField(blank=True, help_text='Ej: 38, 41, 42.5.', max_length=10, verbose_name='talla de zapato'),
        ),
    ]
