# Generated by Django 6.0.6 on 2026-08-18 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_trabajador_puesto_a_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Como figura en la partida de nacimiento.', max_length=200, verbose_name='nombre y apellido')),
                ('fecha_nacimiento', models.DateField()),
                ('documento_identidad', models.CharField(blank=True, help_text='Si ya tiene. Opcional.', max_length=30, verbose_name='cédula')),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_cargados', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='expedientes.trabajador')),
            ],
            options={
                'verbose_name': 'hijo',
                'verbose_name_plural': 'hijos',
                'ordering': ['fecha_nacimiento', 'nombre_completo'],
                'constraints': [models.UniqueConstraint(fields=('trabajador', 'nombre_completo', 'fecha_nacimiento'), name='hijo_no_repetido')],
            },
        ),
    ]
