# Generated by Django 6.0.6 on 2026-08-20 15:47

import expedientes.models
import expedientes.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_hijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=expedientes.storage.AlmacenamientoCifrado(), upload_to=expedientes.models._ruta_documento, validators=[expedientes.models._validar_extension, expedientes.models._validar_tamano]),
        ),
    ]
