# Generated by Django 6.0.6 on 2026-08-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_tipo_de_cedula'),
        ('expedientes', '0011_limite_de_tamano_de_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='La letra que va delante: V, E, J…', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='cuentas.tipodocumentoidentidad', verbose_name='tipo de cédula'),
        ),
    ]
