# Generated by Django 6.0.6 on 2026-08-23 14:50

import django.db.models.deletion
from django.conf import settings
"""Marcar un documento para eliminar, sin poder borrarlo.

RRHH Interior sube un archivo equivocado y hasta ahora no tenia como sacarlo:
borrar es del Administrador. Con esto lo deja pedido y queda en una lista.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_tipo_de_cedula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='marcado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_marcados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='motivo_marca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['marcado_en', 'activo'], name='expedientes_marcado_8c1321_idx'),
        ),
    ]
