# Generated by Django 6.0.6 on 2026-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_marcar_para_eliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontratacion',
            name='ciudad_firma',
            field=models.CharField(blank=True, help_text='Solo si se firma en otra ciudad que la de la tienda. Vacio -lo normal- sale la ciudad de la tienda.', max_length=120, verbose_name='ciudad de firma'),
        ),
    ]
