# Generated by Django 6.0.8 on 2026-08-24 21:34

import expedientes.models
import expedientes.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0015_limpiar_la_ciudad_heredada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=expedientes.storage.AlmacenamientoCifrado(), upload_to=expedientes.models._ruta_documento, validators=[expedientes.models._validar_extension]),
        ),
    ]
