# Generated by Django 6.0.8 on 2026-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0016_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='observaciones_baja',
            field=models.CharField(blank=True, help_text='Motivo o notas cargadas al dar de baja. Se limpia al reactivar; el historial queda en la auditoría.', max_length=400, verbose_name='observaciones de la baja'),
        ),
    ]
