# Generated by Django 6.0.8 on 2026-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0017_trabajador_observaciones_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='rif',
            field=models.CharField(blank=True, help_text='Opcional. El registro fiscal (J-, G-…), distinto de la cédula.', max_length=20, verbose_name='RIF'),
        ),
    ]
