# Generated by Django 6.0.8 on 2026-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0018_trabajador_rif'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'motivo de contratación',
                'verbose_name_plural': 'motivos de contratación',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
